<?xml version="1.0" encoding="utf-8"?><Database Name="db" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\db.mdf;Integrated Security=True" SettingsObjectName="CKD.Properties.Settings" SettingsPropertyName="dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.District" Member="Districts">
    <Type Name="District">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientStatus" Member="PatientStatus">
    <Type Name="PatientStatus">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Title" Member="Titles">
    <Type Name="Title">
      <Column Name="TitleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refAmbulate" Member="refAmbulates">
    <Type Name="refAmbulate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refBalance" Member="refBalances">
    <Type Name="refBalance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refBedMobility" Member="refBedMobilities">
    <Type Name="refBedMobility">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refMMT" Member="refMMTs">
    <Type Name="refMMT">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refTransfer" Member="refTransfers">
    <Type Name="refTransfer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refGender" Member="refGenders">
    <Type Name="refGender">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refDisease" Member="refDiseases">
    <Type Name="refDisease">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.refBMI" Member="refBMIs">
    <Type Name="refBMI">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="min" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="max" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientRecord" Member="PatientRecords">
    <Type Name="PatientRecord">
      <Column Name="recordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="recordDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="eGFR" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="stage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creatinine" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="weight" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="height" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="treatNone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="treatBelly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="treatNeck" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="treatArm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="treatImplants" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="exWalk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="exRun" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="exBite" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="exProgram" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="exReject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="healtEducation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="healtBenefit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="programEx1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="programEx2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="estimate1" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="estimate2" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="estimate3" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="estimate4" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="estimate5" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="estimate6" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="BarthelIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Transfer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BedMobility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ambulate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MMTRightUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MMTRightLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MMTLeftUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MMTLeftLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pain" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Edema" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Other" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Knowlege" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="excercise" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HN" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="TitleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiseaseDM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseHT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseFat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseHeart" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseStroke" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseTB" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseARV" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseOther" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiseaseReject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientRecordDetail" Member="PatientRecordDetails">
    <Type Name="PatientRecordDetail">
      <Column Name="recordDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="recordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Feeding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Transfer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grooming" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Toilet  ]" Member="Toilet__" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bathing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mobility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stair" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dressing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bowels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bladder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>