#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDistrict(District instance);
    partial void UpdateDistrict(District instance);
    partial void DeleteDistrict(District instance);
    partial void InsertPatientStatus(PatientStatus instance);
    partial void UpdatePatientStatus(PatientStatus instance);
    partial void DeletePatientStatus(PatientStatus instance);
    partial void InsertTitle(Title instance);
    partial void UpdateTitle(Title instance);
    partial void DeleteTitle(Title instance);
    partial void InsertrefAmbulate(refAmbulate instance);
    partial void UpdaterefAmbulate(refAmbulate instance);
    partial void DeleterefAmbulate(refAmbulate instance);
    partial void InsertrefBalance(refBalance instance);
    partial void UpdaterefBalance(refBalance instance);
    partial void DeleterefBalance(refBalance instance);
    partial void InsertrefBedMobility(refBedMobility instance);
    partial void UpdaterefBedMobility(refBedMobility instance);
    partial void DeleterefBedMobility(refBedMobility instance);
    partial void InsertrefMMT(refMMT instance);
    partial void UpdaterefMMT(refMMT instance);
    partial void DeleterefMMT(refMMT instance);
    partial void InsertPatientRecordDetail(PatientRecordDetail instance);
    partial void UpdatePatientRecordDetail(PatientRecordDetail instance);
    partial void DeletePatientRecordDetail(PatientRecordDetail instance);
    partial void InsertrefTransfer(refTransfer instance);
    partial void UpdaterefTransfer(refTransfer instance);
    partial void DeleterefTransfer(refTransfer instance);
    partial void InsertrefGender(refGender instance);
    partial void UpdaterefGender(refGender instance);
    partial void DeleterefGender(refGender instance);
    partial void InsertrefDisease(refDisease instance);
    partial void UpdaterefDisease(refDisease instance);
    partial void DeleterefDisease(refDisease instance);
    partial void InsertrefBMI(refBMI instance);
    partial void UpdaterefBMI(refBMI instance);
    partial void DeleterefBMI(refBMI instance);
    partial void InsertPatient(Patient instance);
    partial void UpdatePatient(Patient instance);
    partial void DeletePatient(Patient instance);
    partial void InsertPatientRecord(PatientRecord instance);
    partial void UpdatePatientRecord(PatientRecord instance);
    partial void DeletePatientRecord(PatientRecord instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::CKD.Properties.Settings.Default.dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<District> Districts
		{
			get
			{
				return this.GetTable<District>();
			}
		}
		
		public System.Data.Linq.Table<PatientStatus> PatientStatus
		{
			get
			{
				return this.GetTable<PatientStatus>();
			}
		}
		
		public System.Data.Linq.Table<Title> Titles
		{
			get
			{
				return this.GetTable<Title>();
			}
		}
		
		public System.Data.Linq.Table<refAmbulate> refAmbulates
		{
			get
			{
				return this.GetTable<refAmbulate>();
			}
		}
		
		public System.Data.Linq.Table<refBalance> refBalances
		{
			get
			{
				return this.GetTable<refBalance>();
			}
		}
		
		public System.Data.Linq.Table<refBedMobility> refBedMobilities
		{
			get
			{
				return this.GetTable<refBedMobility>();
			}
		}
		
		public System.Data.Linq.Table<refMMT> refMMTs
		{
			get
			{
				return this.GetTable<refMMT>();
			}
		}
		
		public System.Data.Linq.Table<PatientRecordDetail> PatientRecordDetails
		{
			get
			{
				return this.GetTable<PatientRecordDetail>();
			}
		}
		
		public System.Data.Linq.Table<refTransfer> refTransfers
		{
			get
			{
				return this.GetTable<refTransfer>();
			}
		}
		
		public System.Data.Linq.Table<refGender> refGenders
		{
			get
			{
				return this.GetTable<refGender>();
			}
		}
		
		public System.Data.Linq.Table<refDisease> refDiseases
		{
			get
			{
				return this.GetTable<refDisease>();
			}
		}
		
		public System.Data.Linq.Table<refBMI> refBMIs
		{
			get
			{
				return this.GetTable<refBMI>();
			}
		}
		
		public System.Data.Linq.Table<Patient> Patients
		{
			get
			{
				return this.GetTable<Patient>();
			}
		}
		
		public System.Data.Linq.Table<PatientRecord> PatientRecords
		{
			get
			{
				return this.GetTable<PatientRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.District")]
	public partial class District : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DistrictID;
		
		private string _DistrictName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDistrictIDChanging(int value);
    partial void OnDistrictIDChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    #endregion
		
		public District()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DistrictID
		{
			get
			{
				return this._DistrictID;
			}
			set
			{
				if ((this._DistrictID != value))
				{
					this.OnDistrictIDChanging(value);
					this.SendPropertyChanging();
					this._DistrictID = value;
					this.SendPropertyChanged("DistrictID");
					this.OnDistrictIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="NVarChar(100)")]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatientStatus")]
	public partial class PatientStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StatusID;
		
		private string _StatusDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStatusIDChanging(int value);
    partial void OnStatusIDChanged();
    partial void OnStatusDescChanging(string value);
    partial void OnStatusDescChanged();
    #endregion
		
		public PatientStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this.OnStatusIDChanging(value);
					this.SendPropertyChanging();
					this._StatusID = value;
					this.SendPropertyChanged("StatusID");
					this.OnStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDesc", DbType="NVarChar(50)")]
		public string StatusDesc
		{
			get
			{
				return this._StatusDesc;
			}
			set
			{
				if ((this._StatusDesc != value))
				{
					this.OnStatusDescChanging(value);
					this.SendPropertyChanging();
					this._StatusDesc = value;
					this.SendPropertyChanged("StatusDesc");
					this.OnStatusDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Title")]
	public partial class Title : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TitleID;
		
		private string _TitleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTitleIDChanging(int value);
    partial void OnTitleIDChanged();
    partial void OnTitleNameChanging(string value);
    partial void OnTitleNameChanged();
    #endregion
		
		public Title()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TitleID
		{
			get
			{
				return this._TitleID;
			}
			set
			{
				if ((this._TitleID != value))
				{
					this.OnTitleIDChanging(value);
					this.SendPropertyChanging();
					this._TitleID = value;
					this.SendPropertyChanged("TitleID");
					this.OnTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleName", DbType="NVarChar(50)")]
		public string TitleName
		{
			get
			{
				return this._TitleName;
			}
			set
			{
				if ((this._TitleName != value))
				{
					this.OnTitleNameChanging(value);
					this.SendPropertyChanging();
					this._TitleName = value;
					this.SendPropertyChanged("TitleName");
					this.OnTitleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refAmbulate")]
	public partial class refAmbulate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refAmbulate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refBalance")]
	public partial class refBalance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refBalance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refBedMobility")]
	public partial class refBedMobility : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refBedMobility()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refMMT")]
	public partial class refMMT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refMMT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatientRecordDetail")]
	public partial class PatientRecordDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recordDetailID;
		
		private System.Nullable<int> _recordID;
		
		private System.Nullable<int> _Feeding;
		
		private System.Nullable<int> _Transfer;
		
		private System.Nullable<int> _Grooming;
		
		private System.Nullable<int> _Toilet__;
		
		private System.Nullable<int> _Bathing;
		
		private System.Nullable<int> _Mobility;
		
		private System.Nullable<int> _Stair;
		
		private System.Nullable<int> _Dressing;
		
		private System.Nullable<int> _Bowels;
		
		private System.Nullable<int> _Bladder;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrecordDetailIDChanging(int value);
    partial void OnrecordDetailIDChanged();
    partial void OnrecordIDChanging(System.Nullable<int> value);
    partial void OnrecordIDChanged();
    partial void OnFeedingChanging(System.Nullable<int> value);
    partial void OnFeedingChanged();
    partial void OnTransferChanging(System.Nullable<int> value);
    partial void OnTransferChanged();
    partial void OnGroomingChanging(System.Nullable<int> value);
    partial void OnGroomingChanged();
    partial void OnToilet__Changing(System.Nullable<int> value);
    partial void OnToilet__Changed();
    partial void OnBathingChanging(System.Nullable<int> value);
    partial void OnBathingChanged();
    partial void OnMobilityChanging(System.Nullable<int> value);
    partial void OnMobilityChanged();
    partial void OnStairChanging(System.Nullable<int> value);
    partial void OnStairChanged();
    partial void OnDressingChanging(System.Nullable<int> value);
    partial void OnDressingChanged();
    partial void OnBowelsChanging(System.Nullable<int> value);
    partial void OnBowelsChanged();
    partial void OnBladderChanging(System.Nullable<int> value);
    partial void OnBladderChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
		
		public PatientRecordDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordDetailID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int recordDetailID
		{
			get
			{
				return this._recordDetailID;
			}
			set
			{
				if ((this._recordDetailID != value))
				{
					this.OnrecordDetailIDChanging(value);
					this.SendPropertyChanging();
					this._recordDetailID = value;
					this.SendPropertyChanged("recordDetailID");
					this.OnrecordDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordID", DbType="Int")]
		public System.Nullable<int> recordID
		{
			get
			{
				return this._recordID;
			}
			set
			{
				if ((this._recordID != value))
				{
					this.OnrecordIDChanging(value);
					this.SendPropertyChanging();
					this._recordID = value;
					this.SendPropertyChanged("recordID");
					this.OnrecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feeding", DbType="Int")]
		public System.Nullable<int> Feeding
		{
			get
			{
				return this._Feeding;
			}
			set
			{
				if ((this._Feeding != value))
				{
					this.OnFeedingChanging(value);
					this.SendPropertyChanging();
					this._Feeding = value;
					this.SendPropertyChanged("Feeding");
					this.OnFeedingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfer", DbType="Int")]
		public System.Nullable<int> Transfer
		{
			get
			{
				return this._Transfer;
			}
			set
			{
				if ((this._Transfer != value))
				{
					this.OnTransferChanging(value);
					this.SendPropertyChanging();
					this._Transfer = value;
					this.SendPropertyChanged("Transfer");
					this.OnTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grooming", DbType="Int")]
		public System.Nullable<int> Grooming
		{
			get
			{
				return this._Grooming;
			}
			set
			{
				if ((this._Grooming != value))
				{
					this.OnGroomingChanging(value);
					this.SendPropertyChanging();
					this._Grooming = value;
					this.SendPropertyChanged("Grooming");
					this.OnGroomingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Toilet  ]", Storage="_Toilet__", DbType="Int")]
		public System.Nullable<int> Toilet__
		{
			get
			{
				return this._Toilet__;
			}
			set
			{
				if ((this._Toilet__ != value))
				{
					this.OnToilet__Changing(value);
					this.SendPropertyChanging();
					this._Toilet__ = value;
					this.SendPropertyChanged("Toilet__");
					this.OnToilet__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bathing", DbType="Int")]
		public System.Nullable<int> Bathing
		{
			get
			{
				return this._Bathing;
			}
			set
			{
				if ((this._Bathing != value))
				{
					this.OnBathingChanging(value);
					this.SendPropertyChanging();
					this._Bathing = value;
					this.SendPropertyChanged("Bathing");
					this.OnBathingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobility", DbType="Int")]
		public System.Nullable<int> Mobility
		{
			get
			{
				return this._Mobility;
			}
			set
			{
				if ((this._Mobility != value))
				{
					this.OnMobilityChanging(value);
					this.SendPropertyChanging();
					this._Mobility = value;
					this.SendPropertyChanged("Mobility");
					this.OnMobilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stair", DbType="Int")]
		public System.Nullable<int> Stair
		{
			get
			{
				return this._Stair;
			}
			set
			{
				if ((this._Stair != value))
				{
					this.OnStairChanging(value);
					this.SendPropertyChanging();
					this._Stair = value;
					this.SendPropertyChanged("Stair");
					this.OnStairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dressing", DbType="Int")]
		public System.Nullable<int> Dressing
		{
			get
			{
				return this._Dressing;
			}
			set
			{
				if ((this._Dressing != value))
				{
					this.OnDressingChanging(value);
					this.SendPropertyChanging();
					this._Dressing = value;
					this.SendPropertyChanged("Dressing");
					this.OnDressingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bowels", DbType="Int")]
		public System.Nullable<int> Bowels
		{
			get
			{
				return this._Bowels;
			}
			set
			{
				if ((this._Bowels != value))
				{
					this.OnBowelsChanging(value);
					this.SendPropertyChanging();
					this._Bowels = value;
					this.SendPropertyChanged("Bowels");
					this.OnBowelsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bladder", DbType="Int")]
		public System.Nullable<int> Bladder
		{
			get
			{
				return this._Bladder;
			}
			set
			{
				if ((this._Bladder != value))
				{
					this.OnBladderChanging(value);
					this.SendPropertyChanging();
					this._Bladder = value;
					this.SendPropertyChanged("Bladder");
					this.OnBladderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refTransfer")]
	public partial class refTransfer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refTransfer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refGender")]
	public partial class refGender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refGender()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refDisease")]
	public partial class refDisease : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public refDisease()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(50)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.refBMI")]
	public partial class refBMI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<decimal> _min;
		
		private System.Nullable<decimal> _max;
		
		private string _detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnminChanging(System.Nullable<decimal> value);
    partial void OnminChanged();
    partial void OnmaxChanging(System.Nullable<decimal> value);
    partial void OnmaxChanged();
    partial void OndetailChanging(string value);
    partial void OndetailChanged();
    #endregion
		
		public refBMI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_min", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> min
		{
			get
			{
				return this._min;
			}
			set
			{
				if ((this._min != value))
				{
					this.OnminChanging(value);
					this.SendPropertyChanging();
					this._min = value;
					this.SendPropertyChanged("min");
					this.OnminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> max
		{
			get
			{
				return this._max;
			}
			set
			{
				if ((this._max != value))
				{
					this.OnmaxChanging(value);
					this.SendPropertyChanging();
					this._max = value;
					this.SendPropertyChanged("max");
					this.OnmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detail", DbType="NVarChar(50)")]
		public string detail
		{
			get
			{
				return this._detail;
			}
			set
			{
				if ((this._detail != value))
				{
					this.OndetailChanging(value);
					this.SendPropertyChanging();
					this._detail = value;
					this.SendPropertyChanged("detail");
					this.OndetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patient")]
	public partial class Patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _HN;
		
		private System.Nullable<int> _Number;
		
		private string _Gender;
		
		private System.Nullable<int> _TitleID;
		
		private string _Name;
		
		private string _LastName;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private System.Nullable<int> _DistrictID;
		
		private System.Nullable<int> _StatusID;
		
		private System.Nullable<bool> _DiseaseDM;
		
		private System.Nullable<bool> _DiseaseHT;
		
		private System.Nullable<bool> _DiseaseFat;
		
		private System.Nullable<bool> _DiseaseHeart;
		
		private System.Nullable<bool> _DiseaseStroke;
		
		private System.Nullable<bool> _DiseaseTB;
		
		private System.Nullable<bool> _DiseaseARV;
		
		private System.Nullable<bool> _DiseaseOther;
		
		private System.Nullable<bool> _DiseaseReject;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHNChanging(long value);
    partial void OnHNChanged();
    partial void OnNumberChanging(System.Nullable<int> value);
    partial void OnNumberChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnTitleIDChanging(System.Nullable<int> value);
    partial void OnTitleIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnDistrictIDChanging(System.Nullable<int> value);
    partial void OnDistrictIDChanged();
    partial void OnStatusIDChanging(System.Nullable<int> value);
    partial void OnStatusIDChanged();
    partial void OnDiseaseDMChanging(System.Nullable<bool> value);
    partial void OnDiseaseDMChanged();
    partial void OnDiseaseHTChanging(System.Nullable<bool> value);
    partial void OnDiseaseHTChanged();
    partial void OnDiseaseFatChanging(System.Nullable<bool> value);
    partial void OnDiseaseFatChanged();
    partial void OnDiseaseHeartChanging(System.Nullable<bool> value);
    partial void OnDiseaseHeartChanged();
    partial void OnDiseaseStrokeChanging(System.Nullable<bool> value);
    partial void OnDiseaseStrokeChanged();
    partial void OnDiseaseTBChanging(System.Nullable<bool> value);
    partial void OnDiseaseTBChanged();
    partial void OnDiseaseARVChanging(System.Nullable<bool> value);
    partial void OnDiseaseARVChanged();
    partial void OnDiseaseOtherChanging(System.Nullable<bool> value);
    partial void OnDiseaseOtherChanged();
    partial void OnDiseaseRejectChanging(System.Nullable<bool> value);
    partial void OnDiseaseRejectChanged();
    #endregion
		
		public Patient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long HN
		{
			get
			{
				return this._HN;
			}
			set
			{
				if ((this._HN != value))
				{
					this.OnHNChanging(value);
					this.SendPropertyChanging();
					this._HN = value;
					this.SendPropertyChanged("HN");
					this.OnHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int")]
		public System.Nullable<int> Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleID", DbType="Int")]
		public System.Nullable<int> TitleID
		{
			get
			{
				return this._TitleID;
			}
			set
			{
				if ((this._TitleID != value))
				{
					this.OnTitleIDChanging(value);
					this.SendPropertyChanging();
					this._TitleID = value;
					this.SendPropertyChanged("TitleID");
					this.OnTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictID", DbType="Int")]
		public System.Nullable<int> DistrictID
		{
			get
			{
				return this._DistrictID;
			}
			set
			{
				if ((this._DistrictID != value))
				{
					this.OnDistrictIDChanging(value);
					this.SendPropertyChanging();
					this._DistrictID = value;
					this.SendPropertyChanged("DistrictID");
					this.OnDistrictIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this.OnStatusIDChanging(value);
					this.SendPropertyChanging();
					this._StatusID = value;
					this.SendPropertyChanged("StatusID");
					this.OnStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseDM", DbType="Bit")]
		public System.Nullable<bool> DiseaseDM
		{
			get
			{
				return this._DiseaseDM;
			}
			set
			{
				if ((this._DiseaseDM != value))
				{
					this.OnDiseaseDMChanging(value);
					this.SendPropertyChanging();
					this._DiseaseDM = value;
					this.SendPropertyChanged("DiseaseDM");
					this.OnDiseaseDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseHT", DbType="Bit")]
		public System.Nullable<bool> DiseaseHT
		{
			get
			{
				return this._DiseaseHT;
			}
			set
			{
				if ((this._DiseaseHT != value))
				{
					this.OnDiseaseHTChanging(value);
					this.SendPropertyChanging();
					this._DiseaseHT = value;
					this.SendPropertyChanged("DiseaseHT");
					this.OnDiseaseHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseFat", DbType="Bit")]
		public System.Nullable<bool> DiseaseFat
		{
			get
			{
				return this._DiseaseFat;
			}
			set
			{
				if ((this._DiseaseFat != value))
				{
					this.OnDiseaseFatChanging(value);
					this.SendPropertyChanging();
					this._DiseaseFat = value;
					this.SendPropertyChanged("DiseaseFat");
					this.OnDiseaseFatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseHeart", DbType="Bit")]
		public System.Nullable<bool> DiseaseHeart
		{
			get
			{
				return this._DiseaseHeart;
			}
			set
			{
				if ((this._DiseaseHeart != value))
				{
					this.OnDiseaseHeartChanging(value);
					this.SendPropertyChanging();
					this._DiseaseHeart = value;
					this.SendPropertyChanged("DiseaseHeart");
					this.OnDiseaseHeartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseStroke", DbType="Bit")]
		public System.Nullable<bool> DiseaseStroke
		{
			get
			{
				return this._DiseaseStroke;
			}
			set
			{
				if ((this._DiseaseStroke != value))
				{
					this.OnDiseaseStrokeChanging(value);
					this.SendPropertyChanging();
					this._DiseaseStroke = value;
					this.SendPropertyChanged("DiseaseStroke");
					this.OnDiseaseStrokeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseTB", DbType="Bit")]
		public System.Nullable<bool> DiseaseTB
		{
			get
			{
				return this._DiseaseTB;
			}
			set
			{
				if ((this._DiseaseTB != value))
				{
					this.OnDiseaseTBChanging(value);
					this.SendPropertyChanging();
					this._DiseaseTB = value;
					this.SendPropertyChanged("DiseaseTB");
					this.OnDiseaseTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseARV", DbType="Bit")]
		public System.Nullable<bool> DiseaseARV
		{
			get
			{
				return this._DiseaseARV;
			}
			set
			{
				if ((this._DiseaseARV != value))
				{
					this.OnDiseaseARVChanging(value);
					this.SendPropertyChanging();
					this._DiseaseARV = value;
					this.SendPropertyChanged("DiseaseARV");
					this.OnDiseaseARVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseOther", DbType="Bit")]
		public System.Nullable<bool> DiseaseOther
		{
			get
			{
				return this._DiseaseOther;
			}
			set
			{
				if ((this._DiseaseOther != value))
				{
					this.OnDiseaseOtherChanging(value);
					this.SendPropertyChanging();
					this._DiseaseOther = value;
					this.SendPropertyChanged("DiseaseOther");
					this.OnDiseaseOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiseaseReject", DbType="Bit")]
		public System.Nullable<bool> DiseaseReject
		{
			get
			{
				return this._DiseaseReject;
			}
			set
			{
				if ((this._DiseaseReject != value))
				{
					this.OnDiseaseRejectChanging(value);
					this.SendPropertyChanging();
					this._DiseaseReject = value;
					this.SendPropertyChanged("DiseaseReject");
					this.OnDiseaseRejectChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatientRecord")]
	public partial class PatientRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recordID;
		
		private System.Nullable<long> _HN;
		
		private System.Nullable<System.DateTime> _recordDate;
		
		private System.Nullable<decimal> _eGFR;
		
		private System.Nullable<int> _stage;
		
		private System.Nullable<decimal> _Creatinine;
		
		private System.Nullable<decimal> _weight;
		
		private System.Nullable<decimal> _height;
		
		private System.Nullable<bool> _treatNone;
		
		private System.Nullable<bool> _treatBelly;
		
		private System.Nullable<bool> _treatNeck;
		
		private System.Nullable<bool> _treatArm;
		
		private System.Nullable<bool> _treatImplants;
		
		private System.Nullable<bool> _exWalk;
		
		private System.Nullable<bool> _exRun;
		
		private System.Nullable<bool> _exBite;
		
		private System.Nullable<bool> _exProgram;
		
		private System.Nullable<bool> _exReject;
		
		private System.Nullable<bool> _healtEducation;
		
		private System.Nullable<bool> _healtBenefit;
		
		private System.Nullable<bool> _programEx1;
		
		private System.Nullable<bool> _programEx2;
		
		private System.Nullable<decimal> _estimate1;
		
		private System.Nullable<decimal> _estimate2;
		
		private System.Nullable<decimal> _estimate3;
		
		private System.Nullable<decimal> _estimate4;
		
		private System.Nullable<decimal> _estimate5;
		
		private System.Nullable<decimal> _estimate6;
		
		private System.Nullable<int> _BarthelIndex;
		
		private System.Nullable<int> _Transfer;
		
		private System.Nullable<int> _BedMobility;
		
		private System.Nullable<int> _Balance;
		
		private System.Nullable<int> _Ambulate;
		
		private System.Nullable<int> _MMTRightUE;
		
		private System.Nullable<int> _MMTRightLE;
		
		private System.Nullable<int> _MMTLeftUE;
		
		private System.Nullable<int> _MMTLeftLE;
		
		private System.Nullable<bool> _Tired;
		
		private string _Pain;
		
		private string _Edema;
		
		private string _Other;
		
		private System.Nullable<int> _Knowlege;
		
		private System.Nullable<int> _excercise;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrecordIDChanging(int value);
    partial void OnrecordIDChanged();
    partial void OnHNChanging(System.Nullable<long> value);
    partial void OnHNChanged();
    partial void OnrecordDateChanging(System.Nullable<System.DateTime> value);
    partial void OnrecordDateChanged();
    partial void OneGFRChanging(System.Nullable<decimal> value);
    partial void OneGFRChanged();
    partial void OnstageChanging(System.Nullable<int> value);
    partial void OnstageChanged();
    partial void OnCreatinineChanging(System.Nullable<decimal> value);
    partial void OnCreatinineChanged();
    partial void OnweightChanging(System.Nullable<decimal> value);
    partial void OnweightChanged();
    partial void OnheightChanging(System.Nullable<decimal> value);
    partial void OnheightChanged();
    partial void OntreatNoneChanging(System.Nullable<bool> value);
    partial void OntreatNoneChanged();
    partial void OntreatBellyChanging(System.Nullable<bool> value);
    partial void OntreatBellyChanged();
    partial void OntreatNeckChanging(System.Nullable<bool> value);
    partial void OntreatNeckChanged();
    partial void OntreatArmChanging(System.Nullable<bool> value);
    partial void OntreatArmChanged();
    partial void OntreatImplantsChanging(System.Nullable<bool> value);
    partial void OntreatImplantsChanged();
    partial void OnexWalkChanging(System.Nullable<bool> value);
    partial void OnexWalkChanged();
    partial void OnexRunChanging(System.Nullable<bool> value);
    partial void OnexRunChanged();
    partial void OnexBiteChanging(System.Nullable<bool> value);
    partial void OnexBiteChanged();
    partial void OnexProgramChanging(System.Nullable<bool> value);
    partial void OnexProgramChanged();
    partial void OnexRejectChanging(System.Nullable<bool> value);
    partial void OnexRejectChanged();
    partial void OnhealtEducationChanging(System.Nullable<bool> value);
    partial void OnhealtEducationChanged();
    partial void OnhealtBenefitChanging(System.Nullable<bool> value);
    partial void OnhealtBenefitChanged();
    partial void OnprogramEx1Changing(System.Nullable<bool> value);
    partial void OnprogramEx1Changed();
    partial void OnprogramEx2Changing(System.Nullable<bool> value);
    partial void OnprogramEx2Changed();
    partial void Onestimate1Changing(System.Nullable<decimal> value);
    partial void Onestimate1Changed();
    partial void Onestimate2Changing(System.Nullable<decimal> value);
    partial void Onestimate2Changed();
    partial void Onestimate3Changing(System.Nullable<decimal> value);
    partial void Onestimate3Changed();
    partial void Onestimate4Changing(System.Nullable<decimal> value);
    partial void Onestimate4Changed();
    partial void Onestimate5Changing(System.Nullable<decimal> value);
    partial void Onestimate5Changed();
    partial void Onestimate6Changing(System.Nullable<decimal> value);
    partial void Onestimate6Changed();
    partial void OnBarthelIndexChanging(System.Nullable<int> value);
    partial void OnBarthelIndexChanged();
    partial void OnTransferChanging(System.Nullable<int> value);
    partial void OnTransferChanged();
    partial void OnBedMobilityChanging(System.Nullable<int> value);
    partial void OnBedMobilityChanged();
    partial void OnBalanceChanging(System.Nullable<int> value);
    partial void OnBalanceChanged();
    partial void OnAmbulateChanging(System.Nullable<int> value);
    partial void OnAmbulateChanged();
    partial void OnMMTRightUEChanging(System.Nullable<int> value);
    partial void OnMMTRightUEChanged();
    partial void OnMMTRightLEChanging(System.Nullable<int> value);
    partial void OnMMTRightLEChanged();
    partial void OnMMTLeftUEChanging(System.Nullable<int> value);
    partial void OnMMTLeftUEChanged();
    partial void OnMMTLeftLEChanging(System.Nullable<int> value);
    partial void OnMMTLeftLEChanged();
    partial void OnTiredChanging(System.Nullable<bool> value);
    partial void OnTiredChanged();
    partial void OnPainChanging(string value);
    partial void OnPainChanged();
    partial void OnEdemaChanging(string value);
    partial void OnEdemaChanged();
    partial void OnOtherChanging(string value);
    partial void OnOtherChanged();
    partial void OnKnowlegeChanging(System.Nullable<int> value);
    partial void OnKnowlegeChanged();
    partial void OnexcerciseChanging(System.Nullable<int> value);
    partial void OnexcerciseChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
		
		public PatientRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recordID
		{
			get
			{
				return this._recordID;
			}
			set
			{
				if ((this._recordID != value))
				{
					this.OnrecordIDChanging(value);
					this.SendPropertyChanging();
					this._recordID = value;
					this.SendPropertyChanged("recordID");
					this.OnrecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN", DbType="BigInt")]
		public System.Nullable<long> HN
		{
			get
			{
				return this._HN;
			}
			set
			{
				if ((this._HN != value))
				{
					this.OnHNChanging(value);
					this.SendPropertyChanging();
					this._HN = value;
					this.SendPropertyChanged("HN");
					this.OnHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordDate", DbType="Date")]
		public System.Nullable<System.DateTime> recordDate
		{
			get
			{
				return this._recordDate;
			}
			set
			{
				if ((this._recordDate != value))
				{
					this.OnrecordDateChanging(value);
					this.SendPropertyChanging();
					this._recordDate = value;
					this.SendPropertyChanged("recordDate");
					this.OnrecordDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eGFR", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> eGFR
		{
			get
			{
				return this._eGFR;
			}
			set
			{
				if ((this._eGFR != value))
				{
					this.OneGFRChanging(value);
					this.SendPropertyChanging();
					this._eGFR = value;
					this.SendPropertyChanged("eGFR");
					this.OneGFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stage", DbType="Int")]
		public System.Nullable<int> stage
		{
			get
			{
				return this._stage;
			}
			set
			{
				if ((this._stage != value))
				{
					this.OnstageChanging(value);
					this.SendPropertyChanging();
					this._stage = value;
					this.SendPropertyChanged("stage");
					this.OnstageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creatinine", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Creatinine
		{
			get
			{
				return this._Creatinine;
			}
			set
			{
				if ((this._Creatinine != value))
				{
					this.OnCreatinineChanging(value);
					this.SendPropertyChanging();
					this._Creatinine = value;
					this.SendPropertyChanged("Creatinine");
					this.OnCreatinineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treatNone", DbType="Bit")]
		public System.Nullable<bool> treatNone
		{
			get
			{
				return this._treatNone;
			}
			set
			{
				if ((this._treatNone != value))
				{
					this.OntreatNoneChanging(value);
					this.SendPropertyChanging();
					this._treatNone = value;
					this.SendPropertyChanged("treatNone");
					this.OntreatNoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treatBelly", DbType="Bit")]
		public System.Nullable<bool> treatBelly
		{
			get
			{
				return this._treatBelly;
			}
			set
			{
				if ((this._treatBelly != value))
				{
					this.OntreatBellyChanging(value);
					this.SendPropertyChanging();
					this._treatBelly = value;
					this.SendPropertyChanged("treatBelly");
					this.OntreatBellyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treatNeck", DbType="Bit")]
		public System.Nullable<bool> treatNeck
		{
			get
			{
				return this._treatNeck;
			}
			set
			{
				if ((this._treatNeck != value))
				{
					this.OntreatNeckChanging(value);
					this.SendPropertyChanging();
					this._treatNeck = value;
					this.SendPropertyChanged("treatNeck");
					this.OntreatNeckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treatArm", DbType="Bit")]
		public System.Nullable<bool> treatArm
		{
			get
			{
				return this._treatArm;
			}
			set
			{
				if ((this._treatArm != value))
				{
					this.OntreatArmChanging(value);
					this.SendPropertyChanging();
					this._treatArm = value;
					this.SendPropertyChanged("treatArm");
					this.OntreatArmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treatImplants", DbType="Bit")]
		public System.Nullable<bool> treatImplants
		{
			get
			{
				return this._treatImplants;
			}
			set
			{
				if ((this._treatImplants != value))
				{
					this.OntreatImplantsChanging(value);
					this.SendPropertyChanging();
					this._treatImplants = value;
					this.SendPropertyChanged("treatImplants");
					this.OntreatImplantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exWalk", DbType="Bit")]
		public System.Nullable<bool> exWalk
		{
			get
			{
				return this._exWalk;
			}
			set
			{
				if ((this._exWalk != value))
				{
					this.OnexWalkChanging(value);
					this.SendPropertyChanging();
					this._exWalk = value;
					this.SendPropertyChanged("exWalk");
					this.OnexWalkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exRun", DbType="Bit")]
		public System.Nullable<bool> exRun
		{
			get
			{
				return this._exRun;
			}
			set
			{
				if ((this._exRun != value))
				{
					this.OnexRunChanging(value);
					this.SendPropertyChanging();
					this._exRun = value;
					this.SendPropertyChanged("exRun");
					this.OnexRunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exBite", DbType="Bit")]
		public System.Nullable<bool> exBite
		{
			get
			{
				return this._exBite;
			}
			set
			{
				if ((this._exBite != value))
				{
					this.OnexBiteChanging(value);
					this.SendPropertyChanging();
					this._exBite = value;
					this.SendPropertyChanged("exBite");
					this.OnexBiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exProgram", DbType="Bit")]
		public System.Nullable<bool> exProgram
		{
			get
			{
				return this._exProgram;
			}
			set
			{
				if ((this._exProgram != value))
				{
					this.OnexProgramChanging(value);
					this.SendPropertyChanging();
					this._exProgram = value;
					this.SendPropertyChanged("exProgram");
					this.OnexProgramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exReject", DbType="Bit")]
		public System.Nullable<bool> exReject
		{
			get
			{
				return this._exReject;
			}
			set
			{
				if ((this._exReject != value))
				{
					this.OnexRejectChanging(value);
					this.SendPropertyChanging();
					this._exReject = value;
					this.SendPropertyChanged("exReject");
					this.OnexRejectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_healtEducation", DbType="Bit")]
		public System.Nullable<bool> healtEducation
		{
			get
			{
				return this._healtEducation;
			}
			set
			{
				if ((this._healtEducation != value))
				{
					this.OnhealtEducationChanging(value);
					this.SendPropertyChanging();
					this._healtEducation = value;
					this.SendPropertyChanged("healtEducation");
					this.OnhealtEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_healtBenefit", DbType="Bit")]
		public System.Nullable<bool> healtBenefit
		{
			get
			{
				return this._healtBenefit;
			}
			set
			{
				if ((this._healtBenefit != value))
				{
					this.OnhealtBenefitChanging(value);
					this.SendPropertyChanging();
					this._healtBenefit = value;
					this.SendPropertyChanged("healtBenefit");
					this.OnhealtBenefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programEx1", DbType="Bit")]
		public System.Nullable<bool> programEx1
		{
			get
			{
				return this._programEx1;
			}
			set
			{
				if ((this._programEx1 != value))
				{
					this.OnprogramEx1Changing(value);
					this.SendPropertyChanging();
					this._programEx1 = value;
					this.SendPropertyChanged("programEx1");
					this.OnprogramEx1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programEx2", DbType="Bit")]
		public System.Nullable<bool> programEx2
		{
			get
			{
				return this._programEx2;
			}
			set
			{
				if ((this._programEx2 != value))
				{
					this.OnprogramEx2Changing(value);
					this.SendPropertyChanging();
					this._programEx2 = value;
					this.SendPropertyChanged("programEx2");
					this.OnprogramEx2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate1", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate1
		{
			get
			{
				return this._estimate1;
			}
			set
			{
				if ((this._estimate1 != value))
				{
					this.Onestimate1Changing(value);
					this.SendPropertyChanging();
					this._estimate1 = value;
					this.SendPropertyChanged("estimate1");
					this.Onestimate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate2", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate2
		{
			get
			{
				return this._estimate2;
			}
			set
			{
				if ((this._estimate2 != value))
				{
					this.Onestimate2Changing(value);
					this.SendPropertyChanging();
					this._estimate2 = value;
					this.SendPropertyChanged("estimate2");
					this.Onestimate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate3", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate3
		{
			get
			{
				return this._estimate3;
			}
			set
			{
				if ((this._estimate3 != value))
				{
					this.Onestimate3Changing(value);
					this.SendPropertyChanging();
					this._estimate3 = value;
					this.SendPropertyChanged("estimate3");
					this.Onestimate3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate4", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate4
		{
			get
			{
				return this._estimate4;
			}
			set
			{
				if ((this._estimate4 != value))
				{
					this.Onestimate4Changing(value);
					this.SendPropertyChanging();
					this._estimate4 = value;
					this.SendPropertyChanged("estimate4");
					this.Onestimate4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate5", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate5
		{
			get
			{
				return this._estimate5;
			}
			set
			{
				if ((this._estimate5 != value))
				{
					this.Onestimate5Changing(value);
					this.SendPropertyChanging();
					this._estimate5 = value;
					this.SendPropertyChanged("estimate5");
					this.Onestimate5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimate6", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> estimate6
		{
			get
			{
				return this._estimate6;
			}
			set
			{
				if ((this._estimate6 != value))
				{
					this.Onestimate6Changing(value);
					this.SendPropertyChanging();
					this._estimate6 = value;
					this.SendPropertyChanged("estimate6");
					this.Onestimate6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarthelIndex", DbType="Int")]
		public System.Nullable<int> BarthelIndex
		{
			get
			{
				return this._BarthelIndex;
			}
			set
			{
				if ((this._BarthelIndex != value))
				{
					this.OnBarthelIndexChanging(value);
					this.SendPropertyChanging();
					this._BarthelIndex = value;
					this.SendPropertyChanged("BarthelIndex");
					this.OnBarthelIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfer", DbType="Int")]
		public System.Nullable<int> Transfer
		{
			get
			{
				return this._Transfer;
			}
			set
			{
				if ((this._Transfer != value))
				{
					this.OnTransferChanging(value);
					this.SendPropertyChanging();
					this._Transfer = value;
					this.SendPropertyChanged("Transfer");
					this.OnTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedMobility", DbType="Int")]
		public System.Nullable<int> BedMobility
		{
			get
			{
				return this._BedMobility;
			}
			set
			{
				if ((this._BedMobility != value))
				{
					this.OnBedMobilityChanging(value);
					this.SendPropertyChanging();
					this._BedMobility = value;
					this.SendPropertyChanged("BedMobility");
					this.OnBedMobilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ambulate", DbType="Int")]
		public System.Nullable<int> Ambulate
		{
			get
			{
				return this._Ambulate;
			}
			set
			{
				if ((this._Ambulate != value))
				{
					this.OnAmbulateChanging(value);
					this.SendPropertyChanging();
					this._Ambulate = value;
					this.SendPropertyChanged("Ambulate");
					this.OnAmbulateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMTRightUE", DbType="Int")]
		public System.Nullable<int> MMTRightUE
		{
			get
			{
				return this._MMTRightUE;
			}
			set
			{
				if ((this._MMTRightUE != value))
				{
					this.OnMMTRightUEChanging(value);
					this.SendPropertyChanging();
					this._MMTRightUE = value;
					this.SendPropertyChanged("MMTRightUE");
					this.OnMMTRightUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMTRightLE", DbType="Int")]
		public System.Nullable<int> MMTRightLE
		{
			get
			{
				return this._MMTRightLE;
			}
			set
			{
				if ((this._MMTRightLE != value))
				{
					this.OnMMTRightLEChanging(value);
					this.SendPropertyChanging();
					this._MMTRightLE = value;
					this.SendPropertyChanged("MMTRightLE");
					this.OnMMTRightLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMTLeftUE", DbType="Int")]
		public System.Nullable<int> MMTLeftUE
		{
			get
			{
				return this._MMTLeftUE;
			}
			set
			{
				if ((this._MMTLeftUE != value))
				{
					this.OnMMTLeftUEChanging(value);
					this.SendPropertyChanging();
					this._MMTLeftUE = value;
					this.SendPropertyChanged("MMTLeftUE");
					this.OnMMTLeftUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMTLeftLE", DbType="Int")]
		public System.Nullable<int> MMTLeftLE
		{
			get
			{
				return this._MMTLeftLE;
			}
			set
			{
				if ((this._MMTLeftLE != value))
				{
					this.OnMMTLeftLEChanging(value);
					this.SendPropertyChanging();
					this._MMTLeftLE = value;
					this.SendPropertyChanged("MMTLeftLE");
					this.OnMMTLeftLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tired", DbType="Bit")]
		public System.Nullable<bool> Tired
		{
			get
			{
				return this._Tired;
			}
			set
			{
				if ((this._Tired != value))
				{
					this.OnTiredChanging(value);
					this.SendPropertyChanging();
					this._Tired = value;
					this.SendPropertyChanged("Tired");
					this.OnTiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pain", DbType="NVarChar(250)")]
		public string Pain
		{
			get
			{
				return this._Pain;
			}
			set
			{
				if ((this._Pain != value))
				{
					this.OnPainChanging(value);
					this.SendPropertyChanging();
					this._Pain = value;
					this.SendPropertyChanged("Pain");
					this.OnPainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edema", DbType="NVarChar(250)")]
		public string Edema
		{
			get
			{
				return this._Edema;
			}
			set
			{
				if ((this._Edema != value))
				{
					this.OnEdemaChanging(value);
					this.SendPropertyChanging();
					this._Edema = value;
					this.SendPropertyChanged("Edema");
					this.OnEdemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="NVarChar(250)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this.OnOtherChanging(value);
					this.SendPropertyChanging();
					this._Other = value;
					this.SendPropertyChanged("Other");
					this.OnOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knowlege", DbType="Int")]
		public System.Nullable<int> Knowlege
		{
			get
			{
				return this._Knowlege;
			}
			set
			{
				if ((this._Knowlege != value))
				{
					this.OnKnowlegeChanging(value);
					this.SendPropertyChanging();
					this._Knowlege = value;
					this.SendPropertyChanged("Knowlege");
					this.OnKnowlegeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_excercise", DbType="Int")]
		public System.Nullable<int> excercise
		{
			get
			{
				return this._excercise;
			}
			set
			{
				if ((this._excercise != value))
				{
					this.OnexcerciseChanging(value);
					this.SendPropertyChanging();
					this._excercise = value;
					this.SendPropertyChanged("excercise");
					this.OnexcerciseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
